### ISSUE TITLE
Enhancement for Validation of inputs, outputs, unique fields

### ISSUE THREAD

**Issue by hsngerami** [viddotech/videoalchemy#4]
### What would you like to be added?

Enhancement compose validation for inputs, outputs and unique fields.

### Why is this needed?

helping and leading user to have valid ffmpeg command to reduce the probability of ffmpeg errors.

**Comment by ethereal-engineer** [comment]
What is really needed is a yaml schema file that can be referenced in the yaml itself, which then the editor (e.g. vscode, helix) can lint against and provide suggestions and auto-completion with automatically.
https://medium.com/@alexmolev/boost-your-yaml-with-autocompletion-and-validation-b74735268ad7

**Comment by hsngerami** [comment]
@ethereal-engineer thank you for the medium link, but I mean validation base on ffmpeg rules and parameters.

**Comment by ethereal-engineer** [comment]
It may still be able to be done this way. Have a look at the way the developer of resticprofile has done their yaml schema.

**Comment by ethereal-engineer** [comment]
If I am misunderstanding, I'm sorry for the confusion. I just went to try and use the tech and realised that to use it quickly and effectively it would need this instant yaml schema auto completion. I went to issues and thought this was what this issue meant because I hate duplicates. Is I just added notes.
